#!/bin/sh
# Build 'sendmail.tcz' for TCL
. /etc/init.d/tc-functions

TMPDIR='/tmp/sendmail'
TCZ='/tmp/sendmail.tcz'
INSTALL=0

eAbort() {
	echo "${RED}${1}${NORMAL}"
	exit 1
}
noteInstall() {
    cat <<NT
${BLUE}Copy these in '${tcedir}/optional' and add the extension to 'onboot' list.

Sendmail expect config files in '/etc/mail' and don't like symbolic links.
When the extension is loaded at boot, they are in '/usr/local/etc'.
Either add in 'bootlocal.sh' statement to copy the configuration files
or setup persistense your way.${NORMAL}
NT
}
usage() {
	cat <<USG
${WHITE}usage: `basename $0` [-i]${NORMAL}

If '-i' option is provided -- the TCZ shall be installed
Otherwise the extension shall be in '/tmp'
USG
	exit 1
}

# Parse args
while [ "${1}" ]; do
	case "${1}" in
		--help) usage;;
		-i) INSTALL=1;;
		 *) echo "${YELLOW}unknown option '${1}'";;
	esac
	shift
done

if [ ! -d obj* ]; then eAbort './Build first please'; fi
echo "${BLUE}building 'sendmail.tcz'${NORMAL}"

# Build sendmail.cf if necessary
if [ ! -f cf/cf/sendmail.cf ]; then
	cd cf/cf
	./Build sendmail.cf
	cd ../..
fi
DOMAIN=`grep Dj cf/cf/sendmail.cf`

# Go to the built
cd obj.* 2>/dev/null
if [ $? -ne 0 ]; then eAbort 'Did you ./Build?'; fi
if [ ! -x sendmail/sendmail ]; then eAbort 'Did you ./Build sendmail?'; fi

# Prepare work folder for the extension and populate
[ -d "${TMPDIR}" ] && rm -rf "${TMPDIR}"
# Spool
DST="${TMPDIR}/var/spool"
for f in clientmqueue mqueue; do
    mkdir -p "${DST}/${f}"
    chmod 0640 "${DST}/${f}"
    sudo chown root "${DST}/${f}"
done
DST="${TMPDIR}/usr/local/etc/mail"
# Config
mkdir -p "${DST}"
for f in sendmail.cf submit.cf; do
    cp ../cf/cf/"${f}" "${DST}"
done
touch "${DST}"/local-host-names
cat <<ALIAS > "${DST}"/aliases
MAILER-DAEMON: postmaster
postmaster: root
root: root@${DOMAIN}
${USER}: ${USER}@${DOMAIN}
ALIAS
# Touch the smmsp user
sed -i 's/=smmsp/=tc/' "${DST}"/*.cf
chmod 0640 "${DST}"/*
chmod 0750 "${DST}"
sudo chown -R root "${DST}"
# Binaries
mkdir -p "${TMPDIR}"/usr/local/bin
ls | while read d; do
	if [ -x "${d}/${d}" ]; then cp "${d}/${d}" "${TMPDIR}/usr/local/bin"; fi
done

# Build the extension
if [ -f "${TCZ}" ]; then rm -f "${TCZ}"; fi
mksquashfs "${TMPDIR}/" "${TCZ}" > /dev/null
#rm -rf "${TMPDIR}"
md5sum "${TCZ}" > "${TCZ}.md5.txt"
echo 'db.tcz' > "${TCZ}.dep"

tcedir=`readlink /etc/sysconfig/tcedir`
if [ $INSTALL -ne 0 ]; then
	# Install the extension if requested
	echo "${BLUE}move '${TCZ}*' to '${tcedir}/optional'${NORMAL}"
	cp -f "${TCZ}" "${tcedir}/optional"
	cp -f "${TCZ}.dep" "${tcedir}/optional"
	cp -f "${TCZ}.md5.txt" "${tcedir}/optional"
	echo "${BLUE}adjust '${tcedir}/onboot.lst'${NORMAL}"
	grep -v sendmail.tcz "${tcedir}/onboot.lst" > /tmp/onboot.lst
	echo 'sendmail.tcz' >> /tmp/onboot.lst
	mv -f /tmp/onboot.lst "${tcedir}/"
	tail -n 1 "${tcedir}/onboot.lst"
else
	# or show the extension if not
	echo "${GREEN}done${NORMAL}"
	ls -1 /tmp/sendmail.tcz*
    noteInstall
fi
