#!/bin/sh
# Build 'sendmail.tcz' for TCL
. /etc/init.d/tc-functions

TMPDIR='/tmp/sendmail'
TCZ='/tmp/sendmail.tcz'

eAbort() {
	echo "${RED}${1}${NORMAL}"
	exit 1
}
usage() {
	echo "usage: `basename $0` [i]nstall"
	echo "if 'i' option passed -- TCZ shall be installed"
	echo "otherwise the TCZ shall be in '/tmp'"
	exit 1
}

if [ "${1}" == "--help" ]; then usage; fi

echo "${BLUE}building 'sendmail.tcz'${NORMAL}"
if [ -d "${TMPDIR}" ]; then rm -rf "${TMPDIR}"; fi

cd obj.* 2>/dev/null
if [ $? -ne 0 ]; then eAbort 'Did you ./Build?'; fi
if [ ! -x sendmail/sendmail ]; then eAbort 'Did you ./Build sendmail?'; fi

mkdir -p "${TMPDIR}/etc/mail"
cp ../cf/cf/sendmail.cf "${TMPDIR}/etc/mail/"
cp ../cf/cf/submit.cf "${TMPDIR}/etc/mail/"
#echo 'kayca.tk' > "${TMPDIR}/etc/mail/local-host-names"

mkdir -p "${TMPDIR}/usr/local/bin"
ls | while read d; do
	if [ -x "${d}/${d}" ]; then cp "${d}/${d}" "${TMPDIR}/usr/local/bin"; fi
done

if [ -f "${TCZ}" ]; then rm -f "${TCZ}"; fi
mksquashfs "${TMPDIR}/" "${TCZ}" > /dev/null
rm -rf "${TMPDIR}"
md5sum "${TCZ}" > "${TCZ}.md5.txt"

if [ "${1}" == "i" ]; then
	tcedir=`readlink /etc/sysconfig/tcedir`
	echo "${BLUE}move '${TCZ}*' to '${tcedir}/optional'${NORMAL}"
	cp -f "${TCZ}" "${tcedir}/optional"
	cp -f "${TCZ}.md5.txt" "${tcedir}/optional"
	echo "${BLUE}adjust '${tcedir}/onboot.lst'${NORMAL}"
	grep -v sendmail.tcz "${tcedir}/onboot.lst" > /tmp/onboot.lst
	echo 'sendmail.tcz' >> /tmp/onboot.lst
	mv -f /tmp/onboot.lst "${tcedir}/"
	cat "${tcedir}/onboot.lst"
else
	echo "${BLUE}done${NORMAL}"
	ls -1 /tmp/sendmail*
fi
